/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Button`; params?: Router.UnknownInputParams; } | { pathname: `/../components/TextFeild`; params?: Router.UnknownInputParams; } | { pathname: `/../styles/defaultStyles`; params?: Router.UnknownInputParams; } | { pathname: `/../styles/colors`; params?: Router.UnknownInputParams; } | { pathname: `/../components/movieCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/MovieCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/RatingStars`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Button`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/TextFeild`; params?: Router.UnknownOutputParams; } | { pathname: `/../styles/defaultStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/../styles/colors`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/movieCard`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/MovieCard`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/RatingStars`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../components/Button${`?${string}` | `#${string}` | ''}` | `/../components/TextFeild${`?${string}` | `#${string}` | ''}` | `/../styles/defaultStyles${`?${string}` | `#${string}` | ''}` | `/../styles/colors${`?${string}` | `#${string}` | ''}` | `/../components/movieCard${`?${string}` | `#${string}` | ''}` | `/../components/MovieCard${`?${string}` | `#${string}` | ''}` | `/../components/RatingStars${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Button`; params?: Router.UnknownInputParams; } | { pathname: `/../components/TextFeild`; params?: Router.UnknownInputParams; } | { pathname: `/../styles/defaultStyles`; params?: Router.UnknownInputParams; } | { pathname: `/../styles/colors`; params?: Router.UnknownInputParams; } | { pathname: `/../components/movieCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/MovieCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/RatingStars`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
